theme = "blowfish"
baseURL = "https://profrsantana.github.io/"
defaultContentLanguage = "pt-br"
languageCode = "pt-br"

googleAnalytics = "G-EZZPWFKLQR"

enableRobotsTXT = true
enableEmoji = true
summaryLength = 0

buildDrafts = false
buildFuture = false

[pagination]
  pagerSize = 10

[imaging]
  anchor = "Center"

[outputs]
  home = ["HTML", "RSS", "JSON"]
  section = ["HTML", "RSS"]
  taxonomy = ["HTML"]
  term = ["HTML"]

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"

[sitemap]
  changefreq = "daily"
  filename = "sitemap.xml"
  priority = 0.5

[related]
  threshold = 80
  includeNewer = true
  toLower = true

  [[related.indices]]
    name = "series"
    weight = 100

  [[related.indices]]
    name = "tags"
    weight = 80

  [[related.indices]]
    name = "categories"
    weight = 60
