[[main]]
  name = "Home"
  pageRef = "/"
  weight = 10

[[main]]
  name = "Posts"
  pageRef = "posts"
  weight = 20

[[main]]
  name = "Series"
  pageRef = "series"
  weight = 30

[[main]]
  name = "Inscreva-se"
  url = "https://follow.it/blog-prof-rodrigo-santana?leanpub"
  weight = 40
