colorScheme = "blowfish"
defaultAppearance = "light"
autoSwitchAppearance = true

enableSearch = true
enableCodeCopy = true
enableRobotsTXT = true

disableImageOptimization = false

[header]
  layout = "basic"

[footer]
  showMenu = true
  showCopyright = true
  showThemeAttribution = true
  showAppearanceSwitcher = true
  showScrollToTop = true

[homepage]
  layout = "profile"
  showRecent = true
  showRecentItems = 5
  showMoreLink = true
  showMoreLinkDest = "/posts/"
  cardView = false

[article]
  showDate = true
  showDateUpdated = false
  showAuthor = true
  showHero = false
  showBreadcrumbs = false
  showDraftLabel = true
  showHeadingAnchors = true
  showPagination = true
  showReadingTime = true
  showTableOfContents = false
  showTaxonomies = true
  showWordCount = true
  showComments = true
  seriesOpened = true

[list]
  showBreadcrumbs = false
  showSummary = true
  showCards = false
  groupByYear = true
  cardView = false

[sitemap]
  excludedKinds = ["taxonomy", "term"]

[taxonomy]
  showTermCount = true
  showBreadcrumbs = false
  cardView = false

[term]
  showBreadcrumbs = false
  showTableOfContents = false
  groupByYear = false
  cardView = false