
gtagId = "G-EZZPWFKLQR"  # replace with your GA4 Measurement ID

title = "Estudos do Prof Rodrigo Santana"
author = "Rodrigo M B Santana"
description = "Escritos dos meus estudos em Visão Computacional, Agentes de Inteligência Artificial, e outros tópicos relacionados ao meu Doutorado em Ciencias e Tecnologias Espacias no ITA"
profilePicture = "images/eu.jpg"
localizedDates = true
# Format for the single post page
singleDateFormat = "02/01/2006"

# Format for the homepage (index)
indexDateFormat = "02 de Janeiro de 2006"

# Format for list pages (categories, tags, archives)
# Use "02/01" if you only want day/month in lists
listDateFormat = "02/01"

languageCode = "pt-br"
defaultContentLanguage = "pt-br"

readMore = true

[mermaid]
    enable=true



## Math settings
[math]
enable = false  # options: true, false. Enable math support globally, default: false. You can always enable math on per page.
use = "katex"  # options: "katex", "mathjax". default is "katex".

[[socialIcons]]
icon = "fab fa-linkedin"
title = "Linkedin"
url = "https://www.linkedin.com/in/rodrigo-santana-8865294/"

[[socialIcons]]
icon = "fab fa-instagram"
title = "Instagram"
url = "https://www.instagram.com/profrsantana/"

[[socialIcons]]
icon = "fab fa-rust"
title = "Arigos Sobre Rust"
url = "https://embarcados.com.br/author/rodrigombsantana/"

[[socialIcons]]
icon = "fas fa-graduation-cap"
title = "Curriculum Lattes"
url = "http://lattes.cnpq.br/2093996354767369"

[[socialIcons]]
icon = "fas fa-envelope"
title = "Email"
url = "mailto:rodrigombsantana@gmail.com"

[[socialIcons]]
icon = "fas fa-rss"
title = "RSS"
url = "/posts/index.xml"
