baseURL = 'https://profrsantana.github.io/'
locale = 'pt-br'
title = 'Blog Prof Rodrigo Santana'

theme = 'anatole'

[outputs]
  home = ["HTML"]
  section = ["HTML", "RSS"]
  taxonomy = ["HTML"]
  term = ["HTML"]

[caches]
  [caches.images]
    dir = ':cacheDir/images'


[menu]

  [[menu.main]]
  name = "Home"
  identifier = "home"
  weight = 100
  url = "/"

  [[menu.main]]
  name = "Posts"
  weight = 200
  identifier = "posts"
  url = "/posts/"

[[menu.main]]
  name = "Series"
  weight = 200
  identifier = "series"
  url = "/series/"


[taxonomies]
    category = "categories"
    series = "series"
    tag = "tags"

[related]
  threshold = 80
  includeNewer = true
  toLower = true

  [[related.indices]]
      name = "series"
      weight = 100